/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clientes` | `/clientes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/iara` | `/iara`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/juridico` | `/juridico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/processos` | `/processos`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/clientes` | `/clientes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/iara` | `/iara`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/juridico` | `/juridico`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/processos` | `/processos`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/clientes${`?${string}` | `#${string}` | ''}` | `/clientes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configuracoes${`?${string}` | `#${string}` | ''}` | `/configuracoes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/iara${`?${string}` | `#${string}` | ''}` | `/iara${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/juridico${`?${string}` | `#${string}` | ''}` | `/juridico${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/processos${`?${string}` | `#${string}` | ''}` | `/processos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clientes` | `/clientes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracoes` | `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/iara` | `/iara`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/juridico` | `/juridico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/processos` | `/processos`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
